name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: pull-na-maquina
        uses: actions/checkout@v4

      - name: Compilar o codigo
        shell: powershell
        run: |
          .\mvnw clean package -DskipTests

      - name: parar container antigo
        shell: powershell
        run: |
          docker stop chatbot; docker rm chatbot
          exit 0

      - name: Build da imagem docker
        shell: powershell
        run: docker build -t chatbot .

      - name: rodar container
        shell: powershell
        run: docker run -d --name chatbot -p 8000:8000 chatbot