name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: pull-na-maquina
        uses: actions/checkout@v4

      - name: Compilar o codigo
        shell: powershell
        run: |
          .\mvnw clean package -DskipTests

      - name: parar container antigo
        shell: powershell
        run: docker stop chatbot 2>$null docker rm checkout 2>$null; echo "deu certo"

      - name: Build da imagem docker
        run: docker build -t chatbot .

      - name: rodar container
        run: docker run -d --name chatbot -p 8000:8000 chatbot